version: 2
defaults: &defaults
  working_directory: ~/repo

jobs:
  node6:
    <<: *defaults

    docker:
      - image: circleci/node:6

    steps:
      - checkout

      - restore_cache:
          key: node6-v3-{{checksum "package.json"}}-{{arch}}
      - run: npm install
      - save_cache:
          key: node6-v3-{{checksum "package.json"}}-{{arch}}
          paths:
            - node_modules

      - restore_cache:
          key: node6-build-v1-{{checksum "package.json"}}-{{checksum "tsconfig.json"}}-{{arch}}
      - run: npm run prepare
      - save_cache:
          key: node6-build-v1-{{checksum "package.json"}}-{{checksum "tsconfig.json"}}-{{arch}}
          paths:
            - build

      - run: npm test

  node8:
    <<: *defaults

    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: node8-v1-{{checksum "package-lock.json"}}-{{checksum "tsconfig.json"}}-{{arch}}
      - run: npm install
      - save_cache:
          key: node8-v1-{{checksum "package-lock.json"}}-{{checksum "tsconfig.json"}}-{{arch}}
          paths:
            - node_modules
            - build

      - run: npm test

  node10:
    <<: *defaults

    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          key: node10-v1-{{checksum "package-lock.json"}}-{{checksum "tsconfig.json"}}-{{arch}}
      - run: npm install
      - save_cache:
          key: node10-v1-{{checksum "package-lock.json"}}-{{checksum "tsconfig.json"}}-{{arch}}
          paths:
            - node_modules
            - build

      - run: npm test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults

    docker:
      - image: circleci/node:10

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate to NPM
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run: npm publish

workflows:
  version: 2
  test:
    jobs:
      - node8
      - node10
  publish:
    jobs:
      - node8:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - node10:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - node8
            - node10
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

